Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/focal64"

  config.vm.provider "virtualbox" do |vb|
    vb.name = "server"
    vb.memory = "2048"
    vb.cpus = 2
  end

  config.vm.hostname = "server"

  config.vm.synced_folder ".", "/home/vagrant/volume"
#    owner: "www-data", group: "www-data"
  
#  config.vm.network "forwarded_port", guest: 80, host: 8000
#  config.vm.network "forwarded_port", guest: 3306, host: 33060

  config.vm.network "public_network", ip: "192.168.0.11", bridge: "wlo1"
#  config.vm.network "private_network", ip: "192.168.0.15"

  config.vm.provision "shell", path: "provision.sh"
end
